version: "3.7"

services:
  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - db-data-vol:/var/lib/postgresql/data
      - ./src/config/sql-seeders:/docker-entrypoint-initdb.d

  server:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

volumes:
  db-data-vol:
